name: Meson CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes --quiet meson
    - name: Configure
      run: meson setup _build
    - name: Compile
      run: meson compile -C _build
